# Gunakan image dasar Python
FROM python:3.9-slim

# Set work directory di dalam container
WORKDIR /app

# Salin semua file ke dalam container
COPY requirements.txt .

# Instal dependencies
RUN pip install --no-cache-dir -r requirements.txt
